 const {test, expect} = require ('@playwright/test')

test ('Facebook',async ({page})=>{
    await page.goto ('https://www.facebook.com/')
    await page.waitForTimeout (2000)
    await page.press ("(//a[@role='button'])[2]",'Enter')
    await page.waitForTimeout (2000)
    await page.locator ("//input[@name='firstname']").fill("rohit")
    await page.waitForTimeout (2000)
    await page.locator ("//input[@name='lastname']"). fill("sai")
    await page.waitForTimeout (2000)
    await page.locator ("//select[@name='birthday_day']").selectOption("16")
    await page.waitForTimeout (2000)
    await page.locator ("//select[@name='birthday_month']").selectOption("Jul")
    await page.waitForTimeout (2000) 
    await page.selectOption("//select[@name='birthday_year']","1994")  
    await page.waitForTimeout (2000)
    await page.locator ("(//input[@type='radio'])[2]").check()
    await page.waitForTimeout (2000)
    await page.locator ("(//input[@type='text'])[5]").fill("sairohit.ks94")
    await page.waitForTimeout (2000)
    await page.fill ("//input[@type='password']","Goodluck@1055")
    await page.waitForTimeout (2000)
    await page.press ("(//button[@type='submit'])[1]","Enter")
    await page.screenshot ({path:'screenshots/facebook.jpg'})

})